TARGET = gpu-raster-phase18

include ../common.mk

CPPFLAGS += -I../gpu-raster-phase1
CPPFLAGS += -I../gpu-raster-phase4
CPPFLAGS += -I../gpu-raster-phase17

SRCS += \
gpu-raster-phase18.c \

include ../../common.mk
