TARGET = gp1-09-matrix
TYPE = ps-exe

include ../printf.mk

SRCS += \
../../../common/crt0/memory-s.s \
../../../common/crt0/memory-c.c \
../../../common/crt0/crt0.s \
gp1-09-matrix.c \

CPPFLAGS = -I..

include ../../../common.mk
