TARGET = gpu-raster-phase19

include ../common.mk

CPPFLAGS += -I../gpu-raster-phase1
CPPFLAGS += -I../gpu-raster-phase4
CPPFLAGS += -I../gpu-raster-phase17

SRCS += \
gpu-raster-phase19.c \

include ../../common.mk
