TARGET = vram-blit-y
TYPE = ps-exe

include ../printf.mk

SRCS += \
../../../common/crt0/memory-s.s \
../../../common/crt0/memory-c.c \
../../../common/crt0/crt0.s \
vram-blit-y.c \

CPPFLAGS = -I..

include ../../../common.mk
