TARGET = gpu-raster-phase23

include ../common.mk

CPPFLAGS += -I../gpu-raster-phase1
CPPFLAGS += -I../gpu-raster-phase4
CPPFLAGS += -I../../../../third_party/libcester/include

SRCS += \
gpu-raster-phase23.c \

include ../../common.mk
